### ISSUE TITLE
Not following redirects

### ISSUE THREAD

**Issue by demetriusnunes** [niiknow/docker-nginx-image-proxy#13] opened 2017-08-15 14:10 UTC
I have some image URLs that respond with 302 or 301 like this one:

http://imageproxy.niiknow.org/rx/http://images.ingaiasites.com.br/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg

It would be great if image-proxy could follow redirects.

**Comment by demetriusnunes** [comment] 2017-08-15 14:10
Very common for images hosted in S3 to have redirects.

**Comment by noogen** [comment] 2017-08-15 15:54
Actually, this was a consideration in the development of server.conf.  I purposely disable redirect for security reason:  https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf#L48

Additionally, image_filter + intercept_errors (you get that empty pixel - since anything above 300 is consider error) + follow redirect is kind of tricky to do https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf#L66  http://nginx.org/en/docs/http/ngx_http_proxy_module.html#proxy_intercept_errors

Though it's not impossible.  You can setup another server/listener on port, let say 81, and have that work like a CDN proxy redirect.   Let's called it backend that will perform the redirect and caching of source object.  Then just proxy_pass to http://backend/$clean_uri$is_args$args

**Comment by demetriusnunes** [comment] 2017-08-15 17:40
Ok, I see. I gave it a try for a couple of hours to implement what you suggested but I'm no expert in nginx configuration, so no success on my end. Could you provide me a more clear example of the correct configuration for doing this? Couldn't we just set a @handle_redirect route for 301 and 302 and do a simple rewrite of the url?

**Comment by demetriusnunes** [comment] 2017-08-15 17:42
I've just ported my image server from thumbor to this nginx module and I'm loving it. Much faster and more stable. But, thumbor used to follow the redirects and I really don't want to go back to it just because of this issue...

**Comment by noogen** [comment] 2017-08-15 17:56
> Couldn't we just set a @handle_redirect route for 301 and 302 and do a simple rewrite of the url?

Unfortunately, no.  The image_filter module will give you a 415 error because it did not get an actual image data from remote server.  This is similar complexity/situation as handling image_filter or any kind of native nginx modules that handle binary data when working with lua openresty.

Unfortunately, I won't be able to setup an example until later tonight as I'm currently at work.

**Comment by demetriusnunes** [comment] 2017-08-15 17:58
I see. No problem, I'll wait for your example then. Thanks!

**Comment by noogen** [comment] 2017-08-15 18:07
I experienced the same.  I model the service after this module https://github.com/willnorris/imageproxy for easy conversion on my side.  I run about 5-8 servers haproxied in a rancher dockers environment.  It was great at first but it couldn't handle the load and get pretty unstable to the point of often crashing with out of memory (OOM).    Now, my docker/cattles has been running stable for a while/without breaking a sweat.

I do more complicated transformation with the cheap $10 legacy wp Cloudinary service plan.

**Comment by demetriusnunes** [comment] 2017-08-15 18:36
Did you use in-memory caching with imageproxy? Did you figure out what caused the memory leaks?

**Comment by noogen** [comment] 2017-08-15 19:02
Nope, I actually use the s3 caching method - https://github.com/willnorris/imageproxy/issues/58

I have no idea why it start to perform badly.  I'm not a Go programmer so I wasn't about to troubleshoot.   My requirement is simple.  I just need simple resize and I needed something really light weight and perform wells.   It must also be backward compatible with imageproxy.

**Comment by noogen** [comment] 2017-08-16 01:27
Here you go: http://imageproxy.niiknow.org/rx/200/http://images.ingaiasites.com.br/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg?cb=123

It's not pretty.  This is your gist:  https://gist.github.com/noogen/d28c560bb236bae6765c6440c66765dc

Launch the docker with the raw gist SERVER_CONF=https://gist.githubusercontent.com/noogen/d28c560bb236bae6765c6440c66765dc/raw/943275e7fa66187ba952f2d6ff6b3af1f32471ec/image-proxy-test.conf

I recommend you make your own gist or store it somewhere secure URL.  Explain:

The conf is a derived of current server.conf and my cdn.conf here: https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/cdn.conf

Since the cdn conf (port 81) is already doing the cache.  There is no need to cache on port 80, so I remove all of the caching directives and disabled caching here: https://gist.github.com/noogen/d28c560bb236bae6765c6440c66765dc#file-image-proxy-test-conf-L107  Additionally, I was running into some 403 issue from remote servers because I didn't pass in User-Agent so that's why you have this line: https://gist.github.com/noogen/d28c560bb236bae6765c6440c66765dc#file-image-proxy-test-conf-L20

**Comment by noogen** [comment] 2017-08-16 15:58
Nevermind, after taking some time off to think about my response above, the issue was the "User-Agent" after all.  So I added: https://github.com/niiknow/docker-nginx-image-proxy/blob/master/files/etc/nginx/sites-enabled/server.conf#L49

I tried the @handle_redirect first before doing the port 81 route but that didn't work.  Now the @handle_redirect is working correctly.  Separating the reverse proxy did help identified the 403 (access denied) issue that the image api was throwing out.

**Comment by demetriusnunes** [comment] 2017-08-16 17:31
It's almost perfect. I identified an issue where it works the first time when there's cache miss, but fails when there's a second request (cache hit), with these headers:
```
X-ImageProxy-Code:500
X-ImageProxy-Debug:http://?w=400&h=300&q=96&r=0&e=0&cmd=resize&ofmt=
```

Notice the URL is actually missing. I tested this on your server. I'm assuming is running the latest conf.

**Comment by demetriusnunes** [comment] 2017-08-16 18:19
So, since I also have a CDN in front of my server, after removing all the proxy_cache_* directives from your latest server.conf, it's working perfectly!!

You're the man!!

**Comment by demetriusnunes** [comment] 2017-08-16 18:26
I can close this issue now, but let me know if you want to try to fix this issue and still keep the proxy_cache directives.

My final working conf is here: https://gist.github.com/demetriusnunes/796f2f14bffaf1725366d07e6f4be2e7

**Comment by noogen** [comment] 2017-08-16 22:11
I'll have to look into what is causing that 500 as I do not see it in my testing.  It might be a different issue because it can't be the cache.  I actually do not use redirect and like to keep the proxy_cache directive.  It's only a 10m cache.

**Comment by demetriusnunes** [comment] 2017-08-16 22:16
I just did this:
```
➜  ~ curl -I http://imageproxy.niiknow.org/rx/http://images.ingaiasites.com.br/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 16 Aug 2017 22:15:34 GMT
Content-Type: image/jpeg
Content-Length: 84836
Connection: keep-alive
Keep-Alive: timeout=60
Cache-Control: max-age=86400
Accept-Ranges: bytes
Expires: Thu, 17 Aug 2017 22:15:34 GMT
X-ImageProxy-Cache: MISS
X-ImageProxy-Debug: http://ingaiasites-images.s3.amazonaws.com/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg?w=-&h=-&q=96&r=0&e=0&cmd=resize&ofmt=
Cache-Control: public

➜  ~ curl -I http://imageproxy.niiknow.org/rx/http://images.ingaiasites.com.br/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 16 Aug 2017 22:15:40 GMT
Content-Type: image/gif
Content-Length: 43
Connection: keep-alive
Keep-Alive: timeout=60
Last-Modified: Mon, 28 Sep 1970 06:00:00 GMT
X-ImageProxy-Code: 500
X-ImageProxy-Debug: http://?w=-&h=-&q=96&r=0&e=0&cmd=resize&ofmt=
```

**Comment by noogen** [comment] 2017-08-16 22:16
You didn't pass in a resize in your rx.
```
/rx/http
```
there is no parameters, it's parsing the url as parameter.

**Comment by demetriusnunes** [comment] 2017-08-16 22:17
Sorry, same result:
```
➜  ~ curl -I http://imageproxy.niiknow.org/rx/350x300/http://images.ingaiasites.com.br/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 16 Aug 2017 22:17:35 GMT
Content-Type: image/jpeg
Content-Length: 32910
Connection: keep-alive
Keep-Alive: timeout=60
Cache-Control: max-age=86400
Accept-Ranges: bytes
Expires: Thu, 17 Aug 2017 22:17:34 GMT
X-ImageProxy-Cache: MISS
X-ImageProxy-Debug: http://ingaiasites-images.s3.amazonaws.com/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg?w=350&h=300&q=96&r=0&e=0&cmd=resize&ofmt=
Cache-Control: public

➜  ~ curl -I http://imageproxy.niiknow.org/rx/350x300/http://images.ingaiasites.com.br/dmtBYQdKfjyypH9Ho5VU1mbsJDoxJt5Y.jpg
HTTP/1.1 200 OK
Server: nginx
Date: Wed, 16 Aug 2017 22:17:37 GMT
Content-Type: image/gif
Content-Length: 43
Connection: keep-alive
Keep-Alive: timeout=60
Last-Modified: Mon, 28 Sep 1970 06:00:00 GMT
X-ImageProxy-Code: 500
X-ImageProxy-Debug: http://?w=350&h=300&q=96&r=0&e=0&cmd=resize&ofmt=
```

**Comment by noogen** [comment] 2017-08-16 23:02
ic, your curl bypass the client-side cache and so it's using server-side cache.  I couldn't reproduce because I've been testing on browser.  

The problem was because it was serving cache for the old URL and not the redirected URL.   This is fixed.

**Comment by demetriusnunes** [comment] 2017-08-17 11:31
Wow, awesome! Thanks a lot! 👍 🎆 😀

**Comment by demetriusnunes** [comment] 2018-04-04 21:50
Hi Tom, sorry to bother you again. We've just discovered that the current solution does not follow redirects that have a relative location (which is allowed by the HTTP RFC). For example:
```
curl -I http://www.proativaimoveis.com.br/MultiPhotoHandler.ashx\?idfoto\=437079
HTTP/1.1 302 Found
Cache-Control: private
Content-Length: 135
Content-Type: text/html; charset=utf-8
Location: /fotos2/437079.jpg
```

Any easy way to fix that in the configuration?

**Comment by noogen** [comment] 2018-04-05 03:01
try something like this...

Modify the @handle_redirect location, from:
```
    location @handle_redirect {
        set                         $image_uri "$upstream_http_location";
        set_unescape_uri            $clean_uri "http://127.0.0.1/rx/$myargs/$image_uri";
        proxy_cache_bypass          1;
        proxy_pass                  $clean_uri;
    }
```

To:
```
    location @handle_redirect {
        set                         $image_uri "$upstream_http_location";
 
# if relative url, append base path
        if ($image_uri !~ "(http:|https:)") {
            set $image_uri "$protocol://$myhost$image_uri";
        }

        set_unescape_uri            $clean_uri "http://127.0.0.1/rx/$myargs/$image_uri";
        proxy_cache_bypass          1;
        proxy_pass                  $clean_uri;
    }
```

Note/FYI: I'm just thinking out loud and have not really tried it.  Let me know if that does it.

**Comment by noogen** [comment] 2018-09-08 19:44
Not sure if this is still an issue.  I updated the attach server.conf with the suggested change above.  I'm going to close this.

**Closed as completed by noogen** 2018-09-08 19:44 UTC
